# Generated by Django 4.2.11 on 2026-04-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('seguridad', 'Seguridad'), ('archivos', 'Archivos'), ('sesiones', 'Sesiones'), ('general', 'General')], max_length=50)),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Entero'), ('boolean', 'Booleano'), ('date', 'Fecha')], max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametro_sistema',
                'ordering': ['categoria', 'clave'],
            },
        ),
    ]
