# Generated by Django 5.2.7 on 2026-04-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('configuracion', '0002_periodoacademico'),
    ('usuarios', '0002_usuariorol'),
]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='usuario_modifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
