# Generated by Django 4.2.11 on 2026-05-17 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0002_update_usuario_modifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoacademico',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
