# Generated by Django 4.2.11 on 2026-10-05 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0007_parametros_semaforo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=200)),
                ('programa_academico', models.CharField(max_length=200)),
                ('logotipo', models.FileField(blank=True, null=True, upload_to='identidad/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario_actualiza', models.ForeignKey(blank=True, db_column='id_usuario_actualiza_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identidades_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identidad institucional',
                'verbose_name_plural': 'Identidad institucional',
                'db_table': 'identidad_institucional',
            },
        ),
    ]
