# Generated by Django 4.2.11 on 2026-10-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_identidadinstitucional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosistema',
            name='categoria',
            field=models.CharField(choices=[('institucional', 'Institucional'), ('seguridad', 'Seguridad'), ('archivos', 'Archivos'), ('sesiones', 'Sesiones'), ('general', 'General'), ('rendimiento', 'Rendimiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='tipo_dato',
            field=models.CharField(choices=[('string', 'Texto'), ('integer', 'Entero'), ('boolean', 'Booleano'), ('date', 'Fecha'), ('float', 'Decimal')], max_length=20),
        ),
    ]
