# Generated by Django 4.2.11 on 2026-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0014_fk_cascade_autoevaluacion_coevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='es_plantilla',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='nombre_plantilla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
