"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    # SimpleJWT: Librería para autenticación JWT (BE-01)
    # Provee views ready-to-use para login, refresh y logout
    'rest_framework_simplejwt',
    # Token blacklist: Necesario para logout efectivo (BE-05)
    # Permite agregar tokens a lista negra al hacer logout
    'rest_framework_simplejwt.token_blacklist',
    'apps.usuarios',
    'apps.roles',
    'apps.bitacora',
    'apps.configuracion',
    'apps.cursos',
    'apps.equipos',
]

# Configuración de Django REST Framework (BE-01)
# JWT como método de autenticación por defecto
# Todas las vistas que requieran autenticación usarán tokens JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Import timedelta para configurar tiempos de expiración (BE-01)
from datetime import timedelta

# Configuración de SimpleJWT (BE-01, BE-05)
# Define tiempos de vida y comportamientos de los tokens JWT
SIMPLE_JWT = {
    # ACCESS_TOKEN_LIFETIME: Tiempo de vida del token de acceso (BE-01)
    # Usado para todas las solicitudes autenticadas
    # Valor: 1 hora
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=1),
    
    # REFRESH_TOKEN_LIFETIME: Tiempo de vida del token de refresh (BE-01)
    # Usado para obtener nuevos access tokens sin login
    # Valor: 7 días
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    # ROTATE_REFRESH_TOKENS: Rotación automática de refresh tokens (BE-05)
    # Cuando se usa un refresh token, automáticamente se genera uno nuevo
    # Incrementa seguridad evitando reuse de tokens
    'ROTATE_REFRESH_TOKENS': True,
    
    # BLACKLIST_AFTER_ROTATION: Agregar refresh token usado a blacklist (BE-05)
    # Evita que refresh tokens roteados puedan usarse nuevamente
    # Funciona junto con ROTATE_REFRESH_TOKENS
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Usa SQLite en local, Supabase en producción
if config('USE_SUPABASE', default=False, cast=bool):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='postgres'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Custom user model (BE-01)
# Usa el modelo Usuario personalizado en lugar del User por defecto
AUTH_USER_MODEL = 'usuarios.Usuario'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CORS
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173').split(',')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURACIÓN DEL CACHÉ DE DJANGO
# =============================================================================

# Sistema de caché para almacenar datos temporales en memoria.
# Se utiliza principalmente para cachear los parámetros del sistema
# y evitar consultas repetidas a la base de datos.

CACHES = {
    'default': {
        # BACKEND: Usa memoria local para almacenar datos en caché.
        # LocMemCache es un caché en memoria del proceso de Python.
        # Adecuado para desarrollo local y entornos con un solo worker.
        # NOTA: En producción con múltiples workers, cada proceso tendría su
        # propio caché independiente (no compartido). Para producción se
        # recomienda Redis, Memcached, o Base de datos.
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',

        # LOCATION: Nombre único para identificar este caché.
        # Útil cuando hay múltiples cachés o procesos.
        'LOCATION': 'parametros-sistema-cache',

        # TIMEOUT: Tiempo en segundos antes de que expire el caché.
        # 900 segundos = 15 minutos.
        # Pasado este tiempo, la próxima consulta irá a la base de datos
        # y regenerará el caché con los datos actualizados.
        # Este tiempo balancea:
        # - Rendimiento: Evita consultas repetitivas a la BD
        # - Frescura: Los datos no quedan obsoletos por mucho tiempo
        'TIMEOUT': 900,
    }
}

# CORS: Permitir todos los orígenes (necesario para pruebas E2E con Cypress)
CORS_ALLOW_ALL_ORIGINS = True

# =============================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO
# =============================================================================
EMAIL_BACKEND      = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST         = config('EMAIL_HOST',         default='smtp.gmail.com')
EMAIL_PORT         = config('EMAIL_PORT',         default=587, cast=int)
EMAIL_USE_TLS      = config('EMAIL_USE_TLS',      default=True, cast=bool)
EMAIL_HOST_USER    = config('EMAIL_HOST_USER',    default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='ABP Platform <noreply@ufps.edu.co>')
