# Generated by Django 4.2.11 on 2026-10-05 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0026_vista_indicadores_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_autor', models.ForeignKey(db_column='id_autor_id', on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_publicados', to=settings.AUTH_USER_MODEL)),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='cursos.curso')),
                ('id_proyecto', models.ForeignKey(blank=True, db_column='id_proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='cursos.proyecto')),
            ],
            options={
                'db_table': 'anuncio',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='anuncio',
            constraint=models.CheckConstraint(check=models.Q(('id_curso__isnull', False), ('id_proyecto__isnull', False), _connector='OR'), name='anuncio_curso_o_proyecto'),
        ),
    ]
