# Generated by Django 4.2.11 on 2026-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_is_staff_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
