# Generated by Django 4.2.11 on 2026-10-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_codigo_estudiante_to_codigo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nombre'], name='idx_usuario_nombre', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['apellido'], name='idx_usuario_apellido', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['codigo'], name='idx_usuario_codigo', opclasses=['varchar_pattern_ops']),
        ),
    ]
