# Generated by Django 4.2.11 on 2026-04-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_proyecto'),
    ]

    operations = [
        # Drop the index that will be re-created during field alteration.
        # The original OneToOneField generated this index; altering to ForeignKey
        # with the same name causes a conflict.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "proyecto_id_curso_id_14dbacc7";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='cursos.curso'),
        ),
    ]
