# Generated by Django 4.2.11 on 2026-04-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_proyecto_id_curso'),
        ('cursos', '0004_curso_cantidad_max_estudiantes_proyecto_fk'),
        ('cursos', '0004_proyecto_fk'),
    ]

    operations = [
    ]
