# Generated by Django 4.2.11 on 2026-04-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_proyecto_id_curso'),
        ('cursos', '0004_proyecto_fk'),
        ('cursos', '0005_objetivoproyecto'),
    ]

    operations = [
    ]
