# Generated by Django 4.2.11 on 2026-05-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_merge_20260428_1803'),
        ('cursos', '0006_merge_20260428_1747'),
    ]

    operations = [
    ]
