# Generated by Django 4.2.11 on 2026-05-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_merge_20260501_1539'),
        ('cursos', '0007_merge_20260501_1608'),
    ]

    operations = [
    ]
