# Generated by Django 4.2.11 on 2026-05-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_merge_20260501_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoaprendizaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('hito', 'Hito'), ('entrega', 'Entrega'), ('revision', 'Revisión')], default='hito', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='cursos.proyecto')),
            ],
            options={
                'db_table': 'hito_proyecto',
                'ordering': ['fecha_inicio', 'fecha_fin'],
            },
        ),
    ]
