# Generated by Django 4.2.11 on 2026-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_hitoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoaprendizaje',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resultadoaprendizaje',
            name='porcentaje_evaluacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
