# Generated by Django 5.2.7 on 2026-05-04 21:33

from django.db import migrations


def poblar_curso_estudiante(apps, schema_editor):
    MiembroEquipo = apps.get_model('equipos', 'MiembroEquipo')
    CursoEstudiante = apps.get_model('cursos', 'CursoEstudiante')

    pares = set()
    for m in MiembroEquipo.objects.filter(estado='activo').select_related(
        'usuario', 'equipo__proyecto__id_curso'
    ):
        curso_id = m.equipo.proyecto.id_curso_id
        estudiante_id = m.usuario_id
        pares.add((curso_id, estudiante_id))

    for curso_id, estudiante_id in pares:
        CursoEstudiante.objects.get_or_create(
            curso_id=curso_id,
            estudiante_id=estudiante_id,
            defaults={'estado': 'activo'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_add_curso_estudiante'),
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_curso_estudiante, migrations.RunPython.noop),
    ]
