# Generated by Django 4.2.11 on 2026-05-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_actividad_actividaddependencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoestudiante',
            options={'managed': False},
        ),
    ]
