# Generated by Django 4.2.11 on 2026-05-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_actividad_responsable_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoestudiante',
            options={'managed': False},
        ),
    ]
