# Generated by Django 4.2.11 on 2026-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_cursoestudiante_options'),
        ('cursos', '0019_actividad_responsables'),
    ]

    operations = [
    ]
