# Generated by Django 4.2.11 on 2026-05-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_vista_progreso'),
        ('cursos', '0020_merge_20260507_1724'),
    ]

    operations = [
    ]
