# Generated by Django 4.2.11 on 2026-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_merge_0019_vista_progreso_0020_merge_20260507_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaProgresoFase',
            fields=[
                ('id_fase', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_fase', models.CharField(max_length=200)),
                ('estado_fase', models.CharField(max_length=12)),
                ('orden', models.PositiveIntegerField()),
                ('id_proyecto', models.IntegerField()),
                ('porcentaje_almacenado', models.PositiveSmallIntegerField()),
                ('total_actividades', models.IntegerField()),
                ('actividades_completadas', models.IntegerField()),
                ('actividades_en_progreso', models.IntegerField()),
                ('actividades_bloqueadas', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_progreso_fase',
                'ordering': ['id_proyecto', 'orden'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProgresoProyecto',
            fields=[
                ('id_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('estado_proyecto', models.CharField(max_length=15)),
                ('total_fases', models.IntegerField()),
                ('fases_completadas', models.IntegerField()),
                ('fases_en_progreso', models.IntegerField()),
                ('porcentaje_progreso', models.IntegerField()),
                ('total_actividades', models.IntegerField()),
                ('actividades_completadas', models.IntegerField()),
            ],
            options={
                'db_table': 'vista_progreso_proyecto',
                'managed': False,
            },
        ),
    ]
