# Generated by Django 4.2.11 on 2026-10-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0026_vista_indicadores_periodo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nombre'], name='idx_curso_nombre', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['codigo'], name='idx_curso_codigo', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['nombre'], name='idx_proyecto_nombre', opclasses=['varchar_pattern_ops']),
        ),
    ]
