# Generated by Django 5.2.7 on 2026-04-21 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=10)),
                ('rol_interno', models.CharField(blank=True, choices=[('lider', 'Líder'), ('desarrollador', 'Desarrollador'), ('disenador', 'Diseñador'), ('tester', 'Tester'), ('analista', 'Analista')], default='', max_length=20)),
                ('descripcion_responsabilidades', models.TextField(blank=True, default='')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='equipos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresías', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('equipo', 'usuario'), name='unique_usuario_por_equipo')],
            },
        ),
    ]
