# Generated by Django 4.2.11 on 2026-04-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS_DENIED', 'Acceso denegado')], max_length=50)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'bitacora_sistema',
                'indexes': [models.Index(fields=['id_usuario'], name='idx_bitacora_usuario'), models.Index(fields=['-fecha_hora'], name='idx_bitacora_fecha'), models.Index(fields=['modulo'], name='idx_bitacora_modulo'), models.Index(fields=['accion'], name='idx_bitacora_accion')],
            },
        ),
    ]
