# Generated by Django 4.2.11 on 2026-04-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacorasistema',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ACCESS_DENIED', 'Acceso denegado'), ('ACCESS', 'Consulta')], max_length=50),
        ),
    ]
