# Generated by Django 4.2.11 on 2026-05-20 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('proyecto', 'Reporte de proyecto'), ('estudiante', 'Reporte de estudiante'), ('equipo', 'Reporte de equipo'), ('indicadores', 'Dashboard de indicadores'), ('tendencia', 'Tendencia histórica')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('parametros', models.JSONField(default=dict)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('listo', 'Listo'), ('error', 'Error')], default='generando', max_length=15)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_disponible', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exportacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
