# Generated by Django 4.2.11 on 2026-05-20 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0023_fix_usuario_fk_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('actividad_vencida', 'Actividad vencida'), ('entregable_pendiente', 'Entregable pendiente'), ('evaluacion_pendiente', 'Evaluación pendiente'), ('bajo_rendimiento', 'Bajo rendimiento')], max_length=40)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('no_leida', 'No leída'), ('leida', 'Leída'), ('descartada', 'Descartada')], default='no_leida', max_length=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('referencia_id', models.BigIntegerField(blank=True, help_text='ID del objeto origen (actividad o entregable)', null=True)),
                ('id_proyecto', models.ForeignKey(blank=True, db_column='id_proyecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cursos.proyecto')),
                ('id_usuario_destino', models.ForeignKey(db_column='id_usuario_destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerta',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(fields=('tipo', 'id_usuario_destino', 'referencia_id'), name='unique_alerta_por_usuario_referencia'),
        ),
    ]
