# Generated by Django 5.2.7 on 2026-06-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('actividad_vencida', 'Actividad vencida'), ('entregable_pendiente', 'Entregable pendiente'), ('entregable_enviado', 'Entregable enviado'), ('evaluacion_pendiente', 'Evaluación pendiente'), ('bajo_rendimiento', 'Bajo rendimiento')], max_length=40),
        ),
    ]
