# Generated by Django 4.2.11 on 2026-10-05 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0002_alter_alerta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='gravedad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.CreateModel(
            name='ColaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('plantilla', models.CharField(choices=[('alerta', 'Alerta'), ('anuncio', 'Anuncio'), ('calificacion', 'Calificación'), ('recordatorio', 'Recordatorio')], max_length=20)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], db_index=True, default='pendiente', max_length=15)),
                ('intentos', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_destino', models.ForeignKey(db_column='id_usuario_destino_id', on_delete=django.db.models.deletion.CASCADE, related_name='correos_encolados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cola_correo',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
