# Generated by Django 4.2.11 on 2026-10-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alerta_gravedad_colacorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('actividad_vencida', 'Actividad vencida'), ('entregable_pendiente', 'Entregable pendiente'), ('entregable_enviado', 'Entregable enviado'), ('evaluacion_pendiente', 'Evaluación pendiente'), ('bajo_rendimiento', 'Bajo rendimiento'), ('recordatorio_vencimiento', 'Recordatorio de vencimiento')], max_length=40),
        ),
    ]
