# Generated by Django 4.2.11 on 2026-05-17 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entregables', '0006_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
