# Generated by Django 4.2.11 on 2026-10-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregables', '0007_fix_usuario_fk_set_null'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entregable',
            index=models.Index(fields=['titulo'], name='idx_entregable_titulo', opclasses=['varchar_pattern_ops']),
        ),
    ]
